### ISSUE TITLE
Duplicate project

### ISSUE THREAD

**Issue by vermiculus** [ionrock/magit-hub#1]
Hey there,

I found your project using a codesearch for `magit-define-popup-action 'magit-dispatch-popup` and it looks like this project does pretty much the same thing as vermiculus/magithub (though this project looks like it's only just started).

Just FYI – feel free to close this issue if you don't care 😄

**Comment by ionrock** [comment]
Thanks for the heads up! This was an idea I never got around to doing, so I'm really glad you picked up the torch. I'll be deleting this repo and looking forward to trying out magithub!
